### ISSUE TITLE
Scoring in Billions

### ISSUE THREAD

**Issue by Ritik-Roshan** [PradyumnaKrishna/Qwiklabs#1]
Please add the secret of scoring billions in qwiklabs speedrun to your repo. 😅

**Comment by Ritik-Roshan** [comment]
![Screenshot_20200630-110342_Chrome](https://user-images.githubusercontent.com/66401972/86087255-6427b600-bac1-11ea-9ab4-0c23dee71394.jpg)

Need help to score like you.

**Comment by Ritik-Roshan** [comment]
I do wanna know ki how the F they known for it

**Comment by PradyumnaKrishna** [comment]
There is no secret in how to score billion. I can help you by providing the scripts and cheatsheet anything else is depends upon you.

There is a bug i dont know it is fixed or not you can try yourself 
It help you in scoring billion
Watch this video : https://youtu.be/VAr1JZ3HAkw
